#!/bin/bash
# Copyright 2021 Ryan Svihla

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.


$DIR/setup && \
$DIR/lint && \
$DIR/test && \
$DIR/build
